name: PR Approval
#
# on:
#   pull_request_target:
#     branches:
#       - main
#     types: [opened] # probably the only one you need

on:
  issue_comment:
    types: [created]
    branches:
      - main


jobs:
  build:
    name: Auto-approve
    runs-on: ubuntu-latest
    #if: github.event.pull_request.user.login == 'prem54'
    if: github.event.issue.pull_request != null # Only trigger if the comment is on a PR
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            const result = await github.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            event: "APPROVE"
            })
            console.log(result.status)
