on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment-$COMMENT on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
          COMMENT: ${{ github.event.comment.body }}
