# on: issue_comment

on:
  pull_request_review:
    types: [submitted]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    #if: ${{ github.event.issue.pull_request }}
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "NUMBER:" ${{ github.event.issue.number }}
          echo "COMMENT:" ${{ github.event.comment.body }}
          echo "Review comment:" ${{ github.event.review.body }}
