name: Download Artifacts

on:
  workflow_run:
    workflows: ["Upload Artifacts"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          gh run download --repo "${{ github.repository}}" --name artifact --dir . "${{ github.run_id }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: buildtest
          #path: ./downloaded-artifacts
          #github-token: ${{ secrets.GH_PAT }}
          #repository: prem54/github-actions-demo
          #run-id: ${{ github.event.workflow_run.id }}

      - name: Verify artifact download
        run: ls -al ./downloaded-artifacts

      - name: Use downloaded artifacts
        run: ls -R
