name: My Git Demo

on:
  push:
    branches:
      - 'repo1'
      
      
jobs:
  build:
    name: Demo-Git
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - uses: EndBug/add-and-commit@v9
        with:
          remove: '~/test.txt'
          message: Show GitHub Actions logo
          committer_name: GitHub Actions
          committer_email: actions@github.com
