name: Pass Dynamic Strategy in GitHub Actions

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - repo1

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_var: ${{ steps.set-output-step.outputs.my_var }}
    steps:
      - name: Set variable in job1
        id: set-output-step
        run: |
          MY_VAR="Hello from Job 1"
          echo "::set-output name=my_var::$MY_VAR"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Print variable from job1
        run: |
          echo "Variable from Job 1: ${{ needs.job1.outputs.my_var }}"
