name: My Git Demo

on:
  push:
    branches:
      - 'repo1'
      
      
jobs:
  build:
    name: Demo-Git
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
