#Test1
name: Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create File
        run: |
          mkdir build
          echo "Hello!" >> build/test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: buildtest
          path: ./build # Adjust this to your build directory
          retention-days: 30

      - name: Verify artifact upload
        run: ls -al ./build

      # - name: Download artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: buildtest
      #     path: ./downloaded-artifacts

      # - name: Verify artifact download
      #   run: ls -al ./downloaded-artifacts

      # - name: Use downloaded artifacts
      #   run: ls -R
