#Test
name: Upload Artifacts

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - repo1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create File
        run: |
          mkdir build
          echo "Hello!" >> build/test.txt

      - name: Echo
        run: |
          echo "Value for GITHUB_HEAD_REF: " $GITHUB_HEAD_REF
          echo "Value for GITHUB_REF: " $GITHUB_REF

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: buildtest
          path: ./build # Adjust this to your build directory
          retention-days: 30

      - name: Verify artifact upload
        run: ls -al ./build
