name: Upload Artifacts

on:
  push:
    branches:
      - repo1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create File
        run: echo "Hello!" >> test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./test.txt # Adjust this to your build directory
